### ISSUE TITLE
Do you have plans to support the flux model ?

### ISSUE THREAD

**Issue by yincangshiwei** [TencentARC/BrushEdit#1]
I am glad that the Tencent team has brought an upgraded version of Brushnet, and the results are also great. But currently it only supports SD1.5, I don't know if the latest models such as XL and Flux will be supported in the future

**Comment by liyaowei-stu** [comment]
We have this plan in place. Additionally, due to computational constraints, we are also seeking potential collaborations to train a more powerful DiT-based all-in-one inpainting model.
