### ISSUE TITLE
What is your motivation for this work？

### ISSUE THREAD

**Issue by bengen-y** [TencentARC/BrushEdit#2]
Your input requires a mask, ADD and REPLACE is the same task. It's like adding an external GPT4-O to execute instructions for two tasks. Don't you think it's unnecessary？

**Comment by liyaowei-stu** [comment]
In our approach, the process for the REPLACE operation involves the MLLM identifying the object to be edited based on the input instructions, and obtaining the mask to be edited via Grounded SAM, a free-form detection model. 
In contrast, the ADD operation has the MLLM directly output the coordinates of a rectangular mask based on the input image and instructions.

When using interactive editing, where the mask is drawn by the user, both operations are the same. However, in another instruction-based setting, we claim to have an instruction-only, white-box, free-form editing agent.

For detailed information, please refer to our paper.😃

**Comment by liyaowei-stu** [comment]
We explore inpainting-based editing tasks, which, compared to inversion-based methods [1], do not require time-consuming diffusion inversion. Additionally, unlike instruction-based work [2], we do not need to collect well-paired data (before-editing and after-editing).

[1] Hertz A, Mokady R, Tenenbaum J, et al. Prompt-to-prompt image editing with cross attention control[J]. arXiv preprint arXiv:2208.01626, 2022.
[2] Brooks T, Holynski A, Efros A A. Instructpix2pix: Learning to follow image editing instructions[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2023: 18392-18402.
