### ISSUE TITLE
some wrong with install diffusers

### ISSUE THREAD

**Issue by shellin-star** [TencentARC/BrushEdit#3]
hi，according to your installation manual, there seems to be some problem installing the diffusers :
`BrushEdit/src/diffusers/utils/import_utils.py", line 720, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.brushnet.pipeline_brushnet because of the following error (look up to see its traceback):

Failed to import diffusers.loaders.single_file because of the following error (look up to see its traceback):
No module named 'diffusers.models' `

**Comment by liyaowei-stu** [comment]
Could you please check if you have the src/diffusers/models source file? I fixed this bug in the latest commit: https://github.com/TencentARC/BrushEdit/commit/e43175ba2ada690ef5f47efad346646d8f01c828.

You can either re-clone the repository or use git pull to fetch the latest version.
