### ISSUE TITLE
some questions about brushedit_app.py

### ISSUE THREAD

**Issue by gecade** [TencentARC/BrushEdit#5]
in the brushedit_app.py I can see the code
**from diffusers import StableDiffusionBrushNetPipeline, BrushNetModel, UniPCMultistepScheduler**
but there is no StableDiffusionBrushNetPipeline and BrushNetModel in diffusers when I pip install it 
how can I get them

**Comment by liyaowei-stu** [comment]
you can install diffusers (implemented in this repo) with:

```pip install -e .```

**Comment by liyaowei-stu** [comment]
We forked diffusers and implemented some classes that comply with the diffusers specifications. For example, StableDiffusionBrushNetPipeline :

https://github.com/TencentARC/BrushEdit/blob/main/src/diffusers/pipelines/brushnet/pipeline_brushnet.py

**Comment by Oguzhanercan** [comment]
Hi @liyaowei-stu , when I followed your instructions for setup, I still got error for diffusers as No module named 'diffusers.models'
. Diffusers version is 0.27.0.dev0 ( I guess as it should be). When I check site-packages, there is only diffusers-dist-info folder, there is no diffusers folder.

**Comment by liyaowei-stu** [comment]
@gecade @Oguzhanercan 
I'm very sorry, I am currently testing. As an alternative, you can use `pip install git+https://github.com/TencentARC/BrushNet.git` as a temporary substitute.

**Comment by liyaowei-stu** [comment]
@gecade @Oguzhanercan 
I re-cloned my code and created a new conda environment from scratch. The `brushedit_app.py` runs normally. Please check if you have the latest commit; if not, please re-clone or run `git pull`. Also, check if you have the `src/diffusers/models` directory; if not, then you do not have the latest commit.

Please try to check and get back to me; I would greatly appreciate it!

**Comment by gecade** [comment]
@liyaowei-stu OK I’ve solved this problem, thanks. One more question, where is the class ‘groundingdino'?You used it in utils.py

**Comment by Oguzhanercan** [comment]
Just tried, latest commit works fine, thanks.
