### ISSUE TITLE
请问这个运行需要什么硬件配置

### ISSUE THREAD

**Issue by Jandown** [TencentARC/BrushEdit#6]
感谢作者的分享，很棒的项目。
请问运行这个项目需要什么显卡，显存多少？

**Comment by liyaowei-stu** [comment]
This will be determined by the resolution of the image you input and the MLLM used.

When using the GPT4o API interface, it can run completely on single 32GB V100 with (640*640px) images.

And when you have 40G of A100, you can run most examples.


But if you want to try larger models like Qwen-72b, llava-34b, you will need more GPU memory.

**Comment by Jandown** [comment]
> This will be determined by the resolution of the image you input and the MLLM used.这将由您输入的图像的分辨率和使用的 MLLM 决定。
> 
> When using the GPT4o API interface, it can run completely on single 32GB V100 with (640*640px) images.使用 GPT4o API 接口时，它可以完全在单个 32GB V100 上运行，带有 （640*640px） 图像。
> 
> And when you have 40G of A100, you can run most examples.当您拥有 40G 的 A100 时，您可以运行大多数示例。
> 
> But if you want to try larger models like Qwen-72b, llava-34b, you will need more GPU memory.但是，如果您想尝试 Qwen-72b、llava-34b 等更大的模型，您将需要更多的 GPU 内存。

Ready to set up locally, when I saw the Qwen-72b, I guessed that consumer grade graphics cards couldn't play it, and indeed couldn't. Thank you for your reply

**Comment by liyaowei-stu** [comment]
You are correct. Currently, we have tested GPT-4o, Qwen-VL-7b, LLaVA-1.6-7b-mistral, and LLaVA-1.6-8b-llama. The results show that GPT-4o has a significant lead in instruction understanding, followed by Qwen-VL-7b. We are currently focusing on zero-shot MLLM reasoning, and a potential exploration direction is to collect data related to this task to fine-tune an open-source MLLM.

**Comment by liyaowei-stu** [comment]
When using gpt4-o, 20GB of VRAM is sufficient at a 640px resolution.

**Comment by xduzhangjiayu** [comment]
> When using gpt4-o, 20GB of VRAM is sufficient at a 640px resolution.

请问MLLM (如GPT-4o, Qwen-VL-7b等）是部署在本地还是云端呀？

**Comment by liyaowei-stu** [comment]
> > When using gpt4-o, 20GB of VRAM is sufficient at a 640px resolution.
> 
> 请问MLLM (如GPT-4o, Qwen-VL-7b等）是部署在本地还是云端呀？

Qwen-VL and other open-source models are deployed locally. GPT4o on the cloud.
