### ISSUE TITLE
Can you make the training data public?

### ISSUE THREAD

**Issue by yeluoo** [TencentARC/BrushEdit#7]
@yxgeee @wondervictor @xinntao @bluestyle97 @bluestyle97

**Comment by liyaowei-stu** [comment]
We have this plan, and currently you can download brushdata as the first version of training data.
https://forms.gle/9TgMZ8tm49UYsZ9s5

**Comment by yeluoo** [comment]
I submitted an application a long time ago, but it has not been approved. This batch of data does not seem to have the background data used for training and elimination mentioned by brushedit. I would like to know your rules for processing this batch of data and more details, or you can share some of the data with me at ly1830343214@gmail.com so that I can train it simply. I will be very grateful! @liyaowei-stu
